.deploy:
  stage: deploy
  dependencies: []
  image: ${DOCKER_DEPLOY_IMAGE_NAME}:${DOCKER_DEPLOY_IMAGE_TAG}
  variables:
    DOCKER_DEPLOY_IMAGE_NAME: redmic/docker-docker-deploy
    DOCKER_DEPLOY_IMAGE_TAG: latest
    SSH_REMOTE: <user@remote>
    DEPLOY_KEY: <rsa-private-key>
    STACK: ${CI_PROJECT_NAME}
    REGISTRY_URL: ${CI_REGISTRY}
    REGISTRY_USER: ${CI_DEPLOY_USER}
    REGISTRY_PASS: ${CI_DEPLOY_PASSWORD}
    SERVICES_TO_CHECK: ${CI_PROJECT_NAME}_${CI_PROJECT_NAME}
    STATUS_CHECK_RETRIES: 10
    STATUS_CHECK_INTERVAL: 20
    STATUS_CHECK_DELAY: 120
    STATUS_CHECK_MIN_HITS: 3
  script: deploy
  environment:
    name: environment
  when: manual
