include:
  - local: '/_deployment.yml'

deploy-branch:
  extends: .deploy
  rules:
    - if: $CI_MERGE_REQUEST_ID ||
          $CI_COMMIT_TAG ||
          $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH
      when: manual
      allow_failure: true

deploy-tag:
  extends: .deploy
  rules:
    - if: $CI_COMMIT_TAG
      when: manual
      allow_failure: true
